config/routes.rb
# typed: true

Rails.application.routes.draw do
  use_doorkeeper_openid_connect
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end
  use_doorkeeper_device_authorization_grant do
    controller device_authorizations: "device_authorizations"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/oauth/device/approve", to: "device_authorizations#approve"
  delete "/oauth/device/destroy", to: "device_authorizations#destroy"

  get "up" => "rails/health#show", :as => :rails_health_check

  resources :domains, param: :host, except: [:new] do
    collection do
      get "request", to: "domains#request_domain"
      post "provision", to: "domains#provision"
    end

    member do
      get "/", to: "records#index"
      get "email"
      get "links"
      get "settings"
      get "show", as: "show"
      patch "transfer"
      resources :records
    end
  end

  scope :admin do
    get "/", to: "admin#index"

    scope :users do
      get "/", to: "admin#users"
      get "/:id/domains", to: "admin#users_domains", as: "admin_users_domains"
    end

    scope :domains do
      get "/", to: "admin#domains"
      get "/review", to: "admin#review"
      post "/review", to: "admin#review_decision"
    end

    scope :developers do
      post "/review", to: "admin#developers_review_decision"
      get "/review", to: "admin#developers_review"
    end

    resources :broadcasts, only: [:index], shallow: true do
      resources :notices
      resources :announcements
    end

    mount MissionControl::Jobs::Engine, at: "/jobs"
    mount Audits1984::Engine => "/console"
  end

  get "users/register"
  post "users/create"
  get "users/email_verification"
  post "users/verify_email"
  patch "users/update"

  get "settings", to: "users#settings"

  get "auth/create_key"
  patch "auth/add_key"
  delete "auth/destroy_key"

  get "auth/login"
  get "auth/logout"
  get "auth/email", as: "auth_email"
  post "auth/verify_code", as: "verify_code"
  patch "auth/update_email_auth"
  # need to send request body, made it POST
  post "auth/verify_key"

  get "auth/unsupported"

  # Defines the root path route ("/")
  root "domains#index"

  namespace :api do
    namespace :v1 do
      resources :domains, param: :host do
        member do
          resources :records, module: "domains"
        end
      end
      get "user", to: "user#show"
      patch "user", to: "user#update"
    end
  end

  namespace :developers do
    get "/", to: redirect("developers/applications")
    resources :applications do
      member do
        post "scopes", to: "applications#add_scope"
        delete "scopes", to: "applications#destroy_scope"

        post "redirect_uris", to: "applications#add_redirect_uri"
        delete "redirect_uris", to: "applications#destroy_redirect_uri"
      end

      collection do
        get "request", to: "applications#request"
        post "provision", to: "applications#provision"
      end
    end
  end
end

app/views/admin/developers_review.html.erb
<main ng-app="starter" no-scroll class="admin" domains="<%= @apps.to_json %>">
  <h1>Review Apps</h1>
    <ion-pane ng-controller="CardsCtrl" >
        <td-cards>
            <td-card ng-repeat="card in cards" on-destroy="cardDestroyed($index)" on-swipe-left="cardSwipedLeft($index)" on-swipe-right="cardSwipedRight($index)" on-partial-swipe="cardPartialSwipe(amt)" class="card-{{$index}}">
              <%= form_with method: :post, class: "image", "ng-controller": "CardCtrl", id: "form-{{card.resource_id}}" do |form| %>
                  <h2>{{card.name}}</h2>
                  <p><b>PLAN</b></p>   
                  <p>{{card.plan}}</p>
                  <p><b>REDIRECT</b></p>   
                  <p>{{card.uri}}</p>
                  <div class="no-text">⛔</div>
                  <div class="yes-text">✅</div>
                  <input type="hidden" name="application_id" value="{{card.resource_id}}"/>
                  <input type="hidden" name="provisional_action" value="" class="action-field" />
              <% end %>
            </td-card>
            <div class="none-left">
              <h2>No more apps to review</h2>
            </div>
        </td-cards>
        <br><br>
        <div class="no-text">REJECT</div>
        <div class="yes-text">APPROVE</div>
    </ion-pane>
</main>

<% content_for :head do %>

<script src="https://code.ionicframework.com/collide/0.0.4/collide.js"></script>
<script src="https://code.ionicframework.com/1.0.0-beta.14/js/ionic.bundle.js"></script>
<script src="https://code.ionicframework.com/contrib/ionic-contrib-tinder-cards/ionic.tdcards.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

<%= javascript_include_tag "tinder", "data-turbo-track": "reload" %>
<% end %>

<%= style_tag nonce: true do %>
@import url("https://code.ionicframework.com/contrib/ionic-contrib-tinder-cards/ionic.tdcards.css");
@import url("https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css");

.pane {
  background: #343434 !important;
}

td-cards {
  display: block;
}

main {
  width: 100%;
  height: 85%;
  position: relative;
  color: #343434;
}

td-card {
  position: absolute;
  left: 50%;
  margin-top: 80px;
  margin-bottom: 40px;
  margin-left: -150px;
  width: 300px;
  height: 300px;

  border: 1px solid #999;
  box-shadow: 0px 1px 3px rgba(0,0,0,0.2);
  border-radius: 6px;
  background: #F5F5F5;
  color: #343434;
  z-index: 1;
}

.none-left {
  position: absolute;
  left: 50%;
  margin-top: 80px;
  margin-bottom: 40px;
  margin-left: -150px;
  width: 300px;
  height: 300px;
  z-index: 0;
}

.none-left > h2 {
  color: #F5F5F5;
  text-align: center;
}

td-card .image {
  position: relative;
  padding: 1rem 1rem;
  display: flex;
  flex-direction: column;
  gap: 0rem;
}

.yes-text {
  position: absolute;
  bottom: 10px;
  right: 10px;
  font-size: 30px;
  color: #41EAD4;
  text-stroke: 0.5px black;
  -webkit-text-stroke: 0.5px black;
  opacity: 1 !important;
}
.no-text {
  position: absolute;
  bottom: 10px;
  left: 10px;
  font-size: 30px;
  color: var(--winter-sky);
  opacity: 1 !important;
}

.fade {
  -webkit-transition: 0.2s opacity linear;
  transition: 0.2s opacity linear;
  opacity: 0;
}

h1 {
  font-size: 3rem;
}

h2 {
  font-size: 30px;
}

.none-left > h2 {
  color: var(--winter-sky);
}

form {
  position: relative;
  height: 100%;
}
<% end %>

app/views/admin/domains.html.erb
<main class="admin p-4">
    <h1 style="font-size: xx-large;" >Domains</h1>
    <br>
    <a href="/admin/domains/review" data-turbo="false" style="text-decoration: underline;color: var(--winter-sky);">Review requests</a>
    <br><br>
    <table class="table table-auto">
        <thead>
            <tr>
                <th>Host</th>
                <th>Dash</th>
            </tr>
        </thead>
        
        <tbody>
            <% @domains.each do |d| %>
                <tr>
                    <td><%= d.host %></td>
                    <td><%= link_to "View", domain_path(d), :style => "color: var(--lemon-glacier)" %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</main>

app/views/admin/index.html.erb
<main class="admin p-4">
    <h1 style="font-size: xx-large;">Adminland</h1>

    <ul>
        <li><a href="/admin/users">- View Users</a></li>
        <li><a href="/admin/domains">- View Domains</a></li>
         <li><a href="/admin/domains/review" data-turbo="false">- Review Domain Requests</a></li>
         <li><a href="/admin/developers/review" data-turbo="false">- Review Developer App Requests</a></li>
         <li><a href="/admin/jobs">- Mission Control (Active Job)</a></li>
         <li><a href="/admin/console">- audits1984 (Console Audits)</a></li>
    </ul>
</main>

<%= style_tag nonce: true do %>
    li {
        margin-top: 0.25rem;
    }

    a {
        color: var(--winter-sky);
    }
<% end %>

app/views/admin/review.html.erb
<main ng-app="starter" no-scroll class="admin" domains="<%= @domains.to_json %>">
  <h1>Review Domains</h1>
    <ion-pane ng-controller="CardsCtrl" >
        <td-cards>
            <td-card ng-repeat="card in cards" on-destroy="cardDestroyed($index)" on-swipe-left="cardSwipedLeft($index)" on-swipe-right="cardSwipedRight($index)" on-partial-swipe="cardPartialSwipe(amt)" class="card-{{$index}}">
              <%= form_with method: :post, class: "image", "ng-controller": "CardCtrl", id: "form-{{card.resource_id}}" do |form| %>
                  <h2>{{card.name}}.obl.ong</h2>
                  <p><b>PLAN</b></p>   
                  <p>{{card.plan}}</p>
                  <div class="no-text">⛔</div>
                  <div class="yes-text">✅</div>
                  <input type="hidden" name="domain_id" value="{{card.resource_id}}"/>
                  <input type="hidden" name="provisional_action" value="" class="action-field" />
              <% end %>
            </td-card>
            <div class="none-left">
              <h2>No more domains to review</h2>
            </div>
        </td-cards>
        <br><br>
        <div class="no-text">REJECT</div>
        <div class="yes-text">APPROVE</div>
    </ion-pane>
</main>

<% content_for :head do %>

<script src="https://code.ionicframework.com/collide/0.0.4/collide.js"></script>
<script src="https://code.ionicframework.com/1.0.0-beta.14/js/ionic.bundle.js"></script>
<script src="https://code.ionicframework.com/contrib/ionic-contrib-tinder-cards/ionic.tdcards.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

<%= javascript_include_tag "tinder", "data-turbo-track": "reload" %>
<% end %>

<%= style_tag nonce: true do %>
@import url("https://code.ionicframework.com/contrib/ionic-contrib-tinder-cards/ionic.tdcards.css");
@import url("https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css");

.pane {
  background: #343434 !important;
}

td-cards {
  display: block;
}

main {
  width: 100%;
  height: 85%;
  position: relative;
  color: #343434;
}

td-card {
  position: absolute;
  left: 50%;
  margin-top: 80px;
  margin-bottom: 40px;
  margin-left: -150px;
  width: 300px;
  height: 300px;

  border: 1px solid #999;
  box-shadow: 0px 1px 3px rgba(0,0,0,0.2);
  border-radius: 6px;
  background: #F5F5F5;
  color: #343434;
  z-index: 1;
}

.none-left {
  position: absolute;
  left: 50%;
  margin-top: 80px;
  margin-bottom: 40px;
  margin-left: -150px;
  width: 300px;
  height: 300px;
  z-index: 0;
}

.none-left > h2 {
  color: #F5F5F5;
  text-align: center;
}

td-card .image {
  position: relative;
  padding: 1rem 1rem;
  display: flex;
  flex-direction: column;
  gap: 0rem;
}

.yes-text {
  position: absolute;
  bottom: 10px;
  right: 10px;
  font-size: 30px;
  color: #41EAD4;
  text-stroke: 0.5px black;
  -webkit-text-stroke: 0.5px black;
  opacity: 1 !important;
}
.no-text {
  position: absolute;
  bottom: 10px;
  left: 10px;
  font-size: 30px;
  color: var(--winter-sky);
  opacity: 1 !important;
}

.fade {
  -webkit-transition: 0.2s opacity linear;
  transition: 0.2s opacity linear;
  opacity: 0;
}

h1 {
  font-size: 3rem;
}

h2 {
  font-size: 30px;
}

.none-left > h2 {
  color: var(--winter-sky);
}

form {
  position: relative;
  height: 100%;
}
<% end %>

app/views/admin/users.html.erb
<main class="admin p-4">
    <h1 style="font-size: xx-large;" >Users</h1>
    <br>
    <table class="table table-auto">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Verified?</th>
                <th>Admin?</th>
                <th>Domains</th>
            </tr>
        </thead>
        
        <tbody>
            <% @users.each do |u| %>
                <tr>
                    <td><%= u.name %></td>
                    <td><%= u.email %></td>
                    <td><%= u.verified? %></td>
                    <td><%= u.admin? %></td>
                    <td><%= link_to "View", admin_users_domains_path(u), :style => "color: var(--lemon-glacier)" %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</main>

app/views/admin/users_domains.html.erb
<main class="admin p-4">
    <h1 style="font-size: xx-large;" >Users / Domains</h1>
    <br>
    <table class="table table-auto">
        <thead>
            <tr>
                <th>Host</th>
                <th>Dash</th>
            </tr>
        </thead>
        
        <tbody>
            <% @domains.each do |d| %>
                <tr>
                    <td><%= d.host %></td>
                    <td><%= link_to "View", domain_path(d), :style => "color: var(--lemon-glacier)" %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</main>