config/routes.rb
# typed: true

Rails.application.routes.draw do
  use_doorkeeper_openid_connect
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end
  use_doorkeeper_device_authorization_grant do
    controller device_authorizations: "device_authorizations"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/oauth/device/approve", to: "device_authorizations#approve"
  delete "/oauth/device/destroy", to: "device_authorizations#destroy"

  get "up" => "rails/health#show", :as => :rails_health_check

  resources :domains, param: :host, except: [:new] do
    collection do
      get "request", to: "domains#request_domain"
      post "provision", to: "domains#provision"
    end

    member do
      get "/", to: "records#index"
      get "email"
      get "links"
      get "settings"
      get "show", as: "show"
      patch "transfer"
      resources :records
    end
  end

  scope :admin do
    get "/", to: "admin#index"

    scope :users do
      get "/", to: "admin#users"
      get "/:id/domains", to: "admin#users_domains", as: "admin_users_domains"
    end

    scope :domains do
      get "/", to: "admin#domains"
      get "/review", to: "admin#review"
      post "/review", to: "admin#review_decision"
    end

    scope :developers do
      post "/review", to: "admin#developers_review_decision"
      get "/review", to: "admin#developers_review"
    end

    resources :broadcasts, only: [:index], shallow: true do
      resources :notices
      resources :announcements
    end

    mount MissionControl::Jobs::Engine, at: "/jobs"
    mount Audits1984::Engine => "/console"
  end

  get "users/register"
  post "users/create"
  get "users/email_verification"
  post "users/verify_email"
  patch "users/update"

  get "settings", to: "users#settings"

  get "auth/create_key"
  patch "auth/add_key"
  delete "auth/destroy_key"

  get "auth/login"
  get "auth/logout"
  get "auth/email", as: "auth_email"
  post "auth/verify_code", as: "verify_code"
  patch "auth/update_email_auth"
  # need to send request body, made it POST
  post "auth/verify_key"

  get "auth/unsupported"

  # Defines the root path route ("/")
  root "domains#index"

  namespace :api do
    namespace :v1 do
      resources :domains, param: :host do
        member do
          resources :records, module: "domains"
        end
      end
      get "user", to: "user#show"
      patch "user", to: "user#update"
    end
  end

  namespace :developers do
    get "/", to: redirect("developers/applications")
    resources :applications do
      member do
        post "scopes", to: "applications#add_scope"
        delete "scopes", to: "applications#destroy_scope"

        post "redirect_uris", to: "applications#add_redirect_uri"
        delete "redirect_uris", to: "applications#destroy_redirect_uri"
      end

      collection do
        get "request", to: "applications#request"
        post "provision", to: "applications#provision"
      end
    end
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_configuration

  def ensure_configuration
    ::Configuration.load

    if !::Configuration.setup?
      redirect_to new_configuration_url
    end
  end
end

app/controllers/developers/applications_controller.rb
class Developers::ApplicationsController < ApplicationController
  nested_layouts "layouts/admin"

  before_action do
    @developers = true
  end

  before_action except: [:index, :request, :provision, :create] do
    if (current_application.provisional? || current_application.owner_id != current_user.id) && !current_user.admin?
      render plain: "403 Forbidden or Provisional Domain", status: 403
    end
  end

  before_action only: [:create] do
    if !current_user.admin?
      render plain: "403 Forbidden", status: 403
    end
  end

  def index
    @user = current_user
    @applications = current_user.oauth_applications
  end

  def show
    @application = current_application
  end

  def add_scope
    @application = current_application
    begin
      @application.update!(scopes: Doorkeeper::OAuth::Scopes.from_array([@application.scopes, params[:scope]]))
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique => e
      flash.notice = e.message
    else
      flash.notice = "Added Scope #{params[:scope]}"
    ensure
      redirect_back(fallback_location: developers_applications_path(id: params[:id]))
    end
  end

  def destroy_scope
    @application = current_application
    scopes = @application.scopes.to_a
    scopes.delete(params[:scope])
    @application.update!(scopes: Doorkeeper::OAuth::Scopes.from_array(scopes))
    redirect_back(fallback_location: developers_applications_path(id: params[:id]), notice: "Destroyed scope #{params[:scope]}")
  end

  def add_redirect_uri
    uri = URI.parse(params[:redirect_uri])
    if uri.scheme != "https"
      redirect_back(fallback_location: developers_applications_path, notice: "URIs must use HTTPS")
      return
    end
    @application = current_application
    uris = @application.redirect_uri.split("\r\n")
    uris.push(params[:redirect_uri])
    begin
      @application.update!(redirect_uri: uris.join("\r\n"))
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique => e
      flash.notice = e.message
    else
      flash.notice = "Added Redirect URI"
    ensure
      redirect_back(fallback_location: developers_applications_path(id: params[:id]))
    end
  end

  def destroy_redirect_uri
    @application = current_application
    uris = @application.redirect_uri.split("\r\n")
    uris.delete(params[:redirect_uri])
    @application.update!(redirect_uri: uris.join("\r\n"))
    redirect_back(fallback_location: developers_applications_path(id: params[:id]), notice: "Destroyed Redirect URI")
  end

  def update
    @application = current_application
    @application.update!(name: params[:name]) if params[:name]
    @application.update!(confidential: params[:confidential].to_i.zero?) if params[:confidential]
    redirect_back(fallback_location: developers_applications_path(id: params[:id]), notice: "Updated application")
  end

  def destroy
    current_application.destroy!
    redirect_to developers_path
  end

  def create
    @application = Doorkeeper::Application.new(name: params[:name], redirect_uri: params[:redirect_uri], confidential: true)
    @application.owner = current_user
    @application.save!
    redirect_to developers_application_path(id: @application.id)
  end

  def provision
    uri = URI.parse(params[:redirect_uri])
    if uri.scheme != "https"
      redirect_back(fallback_location: developers_applications_path, notice: "URIs must use HTTPS")
      return
    end
    @application = Doorkeeper::Application.new(name: params[:name], redirect_uri: params[:redirect_uri], plan: params[:plan], confidential: true, provisional: true)
    @application.owner = current_user
    @application.save!
    redirect_to developers_path

    Admin::NotifyJob.perform_later("
    {
      \"blocks\": [
        {
          \"type\": \"section\",
          \"text\": {
            \"type\": \"mrkdwn\",
            \"text\": \"*Application request: #{@application.name}*\"
          }
        },
        {
          \"type\": \"divider\"
        },
        {
          \"type\": \"section\",
          \"text\": {
            \"type\": \"mrkdwn\",
            \"text\": \"*User*: #{@application.owner.name} (id: #{@application.owner.id})\n\n*Plan*: #{@application.plan}\"
          },
          \"accessory\": {
            \"type\": \"button\",
            \"text\": {
              \"type\": \"plain_text\",
              \"text\": \"Review Developer Apps\",
              \"emoji\": true
            },
            \"value\": \"click_me_123\",
            \"url\": \"https://admin.obl.ong/admin/developers/review\",
            \"action_id\": \"button-action\"
          }
        }
      ]
    }")
  end

  private

  def current_application
    Doorkeeper::Application.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def style_tag(content_or_options_with_block = nil, html_options = {}, &block)
    content =
      if block
        html_options = content_or_options_with_block if content_or_options_with_block.is_a?(Hash)
        capture(&block)
      else
        content_or_options_with_block
      end

    if html_options[:nonce] == true
      html_options[:nonce] = content_security_policy_nonce
    end

    content_tag("style", content.html_safe, html_options)
  end
end

app/helpers/developers/applications_helper.rb
module Developers::ApplicationsHelper
end

app/views/doorkeeper/applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_application_path(application), method: :delete do %>
  <%= submit_tag t('doorkeeper.applications.buttons.destroy'),
                 onclick: "return confirm('#{ t('doorkeeper.applications.confirmations.destroy') }')",
                 class: submit_btn_css %>
<% end %>

app/views/doorkeeper/applications/_form.html.erb
<%= form_for application, url: doorkeeper_submit_path(application), as: :doorkeeper_application, html: { role: 'form' } do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger" data-alert><p><%= t('doorkeeper.applications.form.error') %></p></div>
  <% end %>

  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control #{ 'is-invalid' if application.errors[:name].present? }", required: true %>
      <%= doorkeeper_errors_for application, :name %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :redirect_uri, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_area :redirect_uri, class: "form-control #{ 'is-invalid' if application.errors[:redirect_uri].present? }" %>
      <%= doorkeeper_errors_for application, :redirect_uri %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.redirect_uri') %>
      </span>

      <% if Doorkeeper.configuration.allow_blank_redirect_uri?(application) %>
        <span class="form-text text-secondary">
          <%= t('doorkeeper.applications.help.blank_redirect_uri') %>
        </span>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :confidential, class: 'col-sm-2 form-check-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.check_box :confidential, class: "checkbox #{ 'is-invalid' if application.errors[:confidential].present? }" %>
      <%= doorkeeper_errors_for application, :confidential %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.confidential') %>
      </span>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :scopes, class: 'col-sm-2 col-form-label font-weight-bold' %>
    <div class="col-sm-10">
      <%= f.text_field :scopes, class: "form-control #{ 'has-error' if application.errors[:scopes].present? }" %>
      <%= doorkeeper_errors_for application, :scopes %>
      <span class="form-text text-secondary">
        <%= t('doorkeeper.applications.help.scopes') %>
      </span>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit t('doorkeeper.applications.buttons.submit'), class: 'btn btn-primary' %>
      <%= link_to t('doorkeeper.applications.buttons.cancel'), oauth_applications_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/doorkeeper/applications/edit.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/index.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title') %></h1>
</div>

<p><%= link_to t('.new'), new_oauth_application_path, class: 'btn btn-success' %></p>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.callback_url') %></th>
    <th><%= t('.confidential') %></th>
    <th><%= t('.actions') %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @applications.each do |application| %>
    <tr id="application_<%= application.id %>">
      <td class="align-middle">
        <%= link_to application.name, oauth_application_path(application) %>
      </td>
      <td class="align-middle">
        <%= simple_format(application.redirect_uri) %>
      </td>
      <td class="align-middle">
        <%= application.confidential? ? t('doorkeeper.applications.index.confidentiality.yes') : t('doorkeeper.applications.index.confidentiality.no') %>
      </td>
      <td class="align-middle">
        <%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(application), class: 'btn btn-link' %>
      </td>
      <td class="align-middle">
        <%= render 'delete_form', application: application %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/doorkeeper/applications/new.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/show.html.erb
<div class="border-bottom mb-4">
  <h1><%= t('.title', name: @application.name) %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <h4><%= t('.application_id') %>:</h4>
    <p><code class="bg-light" id="application_id"><%= @application.uid %></code></p>

    <h4><%= t('.secret') %>:</h4>
    <p>
      <code class="bg-light" id="secret">
        <% secret = flash[:application_secret].presence || @application.plaintext_secret %>
        <% if secret.blank? && Doorkeeper.config.application_secret_hashed? %>
          <span class="bg-light font-italic text-uppercase text-muted"><%= t('.secret_hashed') %></span>
        <% else %>
          <%= secret %>
        <% end %>
      </code>
    </p>

    <h4><%= t('.scopes') %>:</h4>
    <p>
      <code class="bg-light" id="scopes">
        <% if @application.scopes.present? %>
          <%= @application.scopes %>
        <% else %>
          <span class="bg-light font-italic text-uppercase text-muted"><%= t('.not_defined') %></span>
        <% end %>
      </code>
    </p>

    <h4><%= t('.confidential') %>:</h4>
    <p><code class="bg-light" id="confidential"><%= @application.confidential? %></code></p>

    <h4><%= t('.callback_urls') %>:</h4>

    <% if @application.redirect_uri.present? %>
      <table>
        <% @application.redirect_uri.split.each do |uri| %>
          <tr>
            <td>
              <code class="bg-light"><%= uri %></code>
            </td>
            <td>
              <%= link_to t('doorkeeper.applications.buttons.authorize'), oauth_authorization_path(client_id: @application.uid, redirect_uri: uri, response_type: 'code', scope: @application.scopes), class: 'btn btn-success', target: '_blank' %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <span class="bg-light font-italic text-uppercase text-muted"><%= t('.not_defined') %></span>
    <% end %>
  </div>

  <div class="col-md-4">
    <h3><%= t('.actions') %></h3>

    <p><%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(@application), class: 'btn btn-primary' %></p>

    <p><%= render 'delete_form', application: @application, submit_btn_css: 'btn btn-danger' %></p>
  </div>
</div>