config/routes.rb
# typed: true

Rails.application.routes.draw do
  use_doorkeeper_openid_connect
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end
  use_doorkeeper_device_authorization_grant do
    controller device_authorizations: "device_authorizations"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/oauth/device/approve", to: "device_authorizations#approve"
  delete "/oauth/device/destroy", to: "device_authorizations#destroy"

  get "up" => "rails/health#show", :as => :rails_health_check

  resources :domains, param: :host, except: [:new] do
    collection do
      get "request", to: "domains#request_domain"
      post "provision", to: "domains#provision"
    end

    member do
      get "/", to: "records#index"
      get "email"
      get "links"
      get "settings"
      get "show", as: "show"
      patch "transfer"
      resources :records
    end
  end

  scope :admin do
    get "/", to: "admin#index"

    scope :users do
      get "/", to: "admin#users"
      get "/:id/domains", to: "admin#users_domains", as: "admin_users_domains"
    end

    scope :domains do
      get "/", to: "admin#domains"
      get "/review", to: "admin#review"
      post "/review", to: "admin#review_decision"
    end

    scope :developers do
      post "/review", to: "admin#developers_review_decision"
      get "/review", to: "admin#developers_review"
    end

    resources :broadcasts, only: [:index], shallow: true do
      resources :notices
      resources :announcements
    end

    mount MissionControl::Jobs::Engine, at: "/jobs"
    mount Audits1984::Engine => "/console"
  end

  get "users/register"
  post "users/create"
  get "users/email_verification"
  post "users/verify_email"
  patch "users/update"

  get "settings", to: "users#settings"

  get "auth/create_key"
  patch "auth/add_key"
  delete "auth/destroy_key"

  get "auth/login"
  get "auth/logout"
  get "auth/email", as: "auth_email"
  post "auth/verify_code", as: "verify_code"
  patch "auth/update_email_auth"
  # need to send request body, made it POST
  post "auth/verify_key"

  get "auth/unsupported"

  # Defines the root path route ("/")
  root "domains#index"

  namespace :api do
    namespace :v1 do
      resources :domains, param: :host do
        member do
          resources :records, module: "domains"
        end
      end
      get "user", to: "user#show"
      patch "user", to: "user#update"
    end
  end

  namespace :developers do
    get "/", to: redirect("developers/applications")
    resources :applications do
      member do
        post "scopes", to: "applications#add_scope"
        delete "scopes", to: "applications#destroy_scope"

        post "redirect_uris", to: "applications#add_redirect_uri"
        delete "redirect_uris", to: "applications#destroy_redirect_uri"
      end

      collection do
        get "request", to: "applications#request"
        post "provision", to: "applications#provision"
      end
    end
  end
end

app/models/domain.rb
class Domain < ApplicationRecord
  include DnsimpleHelper
  validates :host, uniqueness: true # standard:disable all
  validates :host, presence: {message: "Host is not present"}
  validates :user_users_id, presence: {message: "User ID is not present"}

  after_create ->(d) { Domain::InitializeJob.perform_later(d.id) }, unless: proc { |d| d.provisional }

  after_create ->(d) { provisional_notify }, if: proc { |d| d.provisional }
  before_update ->(d) { Domain::InitializeJob.perform_later(d.id) }, if: proc { |d| d.provisional_changed?(from: true, to: false) }

  before_update ->(d) {
                  Domain::DestroyJob.perform_later(d.host)
                  provisional_notify
                }, if: proc { |d| d.provisional_changed?(from: false, to: true) }

  before_destroy ->(d) { Domain::DestroyJob.perform_later(d.host) }, unless: proc { |d| d.provisional }

  after_commit ->(d) {
    Domain::UpdateProvisionalCountJob.perform_later
  }

  encrypts :host, deterministic: true
  encrypts :plan

  def to_param
    host
  end

  def top_records
    records = []
    all_records = Record.where_host(host)

    if all_records.length > 3
      records[0] = all_records[0]
      records[1] = all_records[1]
      records[2] = all_records[2]
    else
      records = all_records
    end

    records
  end

  def records
    Record.where_host(host)
  end

  def user
    User::User.find_by(id: user_users_id)
  end

  def provisional_notify
    Admin::NotifyJob.perform_later("
    {
      \"blocks\": [
        {
          \"type\": \"section\",
          \"text\": {
            \"type\": \"mrkdwn\",
            \"text\": \"*Domain request: #{host}*\"
          }
        },
        {
          \"type\": \"divider\"
        },
        {
          \"type\": \"section\",
          \"text\": {
            \"type\": \"mrkdwn\",
            \"text\": \"*User*: #{user.name} (id: #{user.id})\n\n*Plan*: #{plan}\"
          },
          \"accessory\": {
            \"type\": \"button\",
            \"text\": {
              \"type\": \"plain_text\",
              \"text\": \"Review Domains\",
              \"emoji\": true
            },
            \"value\": \"click_me_123\",
            \"url\": \"https://admin.obl.ong/admin/domains/review\",
            \"action_id\": \"button-action\"
          }
        }
      ]
    }")
  end
end

app/models/domain/resource.rb
class Domain::Resource < ApplicationRecord
  self.table_name = "domain_resources"
  belongs_to :domains

  def self.types
    subclasses.map { |r| r.name.demodulize }
  end
end

app/models/domain/resource/a.rb
class Domain::Resource::A < Domain::Resource
end

app/models/domain/resource/aaaa.rb
class Domain::Resource::AAAA < Domain::Resource
end

app/models/domain/resource/alias.rb
class Domain::Resource::ALIAS < Domain::Resource
end

app/models/domain/resource/caa.rb
class Domain::Resource::CAA < Domain::Resource
end

app/models/domain/resource/cname.rb
class Domain::Resource::CNAME < Domain::Resource
end

app/models/domain/resource/hinfo.rb
class Domain::Resource::HINFO < Domain::Resource
end

app/models/domain/resource/mx.rb
class Domain::Resource::MX < Domain::Resource
end

app/models/domain/resource/naptr.rb
class Domain::Resource::NAPTR < Domain::Resource
end

app/models/domain/resource/ns.rb
class Domain::Resource::NS < Domain::Resource
end

app/models/domain/resource/ptr.rb
class Domain::Resource::PTR < Domain::Resource
end

app/models/domain/resource/spf.rb
class Domain::Resource::SPF < Domain::Resource
end

app/models/domain/resource/srv.rb
class Domain::Resource::SRV < Domain::Resource
end

app/models/domain/resource/sshfp.rb
class Domain::Resource::SSHFP < Domain::Resource
end

app/models/domain/resource/txt.rb
class Domain::Resource::TXT < Domain::Resource
end

app/models/domain/resource/url.rb
class Domain::Resource::URL < Domain::Resource
end

app/controllers/admin/domains_controller.rb
module Admin
  class DomainsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/domains/records_controller.rb
class Api::V1::Domains::RecordsController < Api::V1::ApiController
  include DomainAuthorization
  before_action do
    doorkeeper_authorize! :domains
    doorkeeper_authorize! :domains_records
  end

  before_action only: [:create, :update, :destroy] do
    doorkeeper_authorize! :domains_records_write
  end

  def index
    @records = current_domain.records
  end

  def create
    @record = Record.create(domain_id: current_domain.id, name: params["name"], type: params["type"], content: params["content"], ttl: params["ttl"], priority: params["priority"]) # standard:disable all
    render "show"
  end

  def show
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])

    (@record.type = params[:type]) if params[:type]
    (@record.name = params[:name]) if params[:name]
    (@record.content = params[:content]) if params[:content]
    (@record.ttl = params[:ttl]) if params[:ttl]
    (@record.priority = params[:priority]) if params[:priority]

    @record.save # standard:disable all

    render "show"
  end

  def destroy
    @record = Record.find(params[:id])

    @record.destroy! #standard:disable all

    index
    render "index"
  end
end

app/controllers/api/v1/domains_controller.rb
class Api::V1::DomainsController < Api::V1::ApiController
  include DomainAuthorization
  before_action do
    doorkeeper_authorize! :domains
  end

  before_action only: [:create, :destroy] do
    doorkeeper_authorize! :domains_write
  end

  skip_before_action :authorize_domain, only: [:index, :create]

  def index
    @domains = Domain.where(user_users_id: current_user.id)
    if params[:records]
      doorkeeper_authorize!(:domains_records)
    end
  end

  def show
    @domain = Domain.find_by(host: params[:host])
    if params[:records]
      doorkeeper_authorize!(:domains_records)
    end
  end

  def create
    @domain = Domain.new(host: params[:host], plan: params[:plan], provisional: true, user_users_id: current_user.id)
    if @domain.save
      render "show"
    else
      render json: @domain.errors, status: 418
    end
  end

  def destroy
    @domain = Domain.find_by(host: params[:host])
    @domain.destroy!

    index
    render "index"
  end
end

app/views/domains/_domain.html.erb
<a <% if !domain.provisional %> href="<%= domain_path(domain) %>" <% end %> class="flex flex-col p-4 items-start gap-[1.375rem] bg-text text-black shadow-md rounded-2xl h-full text-ellipsis overflow-clip card">
    <h2 class="leading-none text-3 font-body text-ellipsis">
    <%= domain.host %><span style="opacity: 0.5;"><%= "." + Rails.application.config.domain %></span>
    </h2>
    <div class="flex flex-col items-start gap-2 text-ellipsis overflow-clip">
    <% if !domain.provisional %>
        <% if domain.top_records.length > 0 %>
            <% domain.top_records.each do |r| %>
                <div class="flex flex-row items-center gap-2">
                    <span class="chip-blue text-ellipsis"><%= r.type%></span>
                    <span class="leading-none text-1 max-w-[220px] whitespace-nowrap overflow-hidden text-ellipsis"><%= r.name %> → <%= r.content %></span>
                </div>
            <% end %>
        <% else %>
            <h2> No Records</h2>
        <% end %>
    <% else %>
     <h2>Your domain is under review. <br>Check back soon!</h2>
    <% end %>
    </div>
    <div style="flex-grow: 1;width: 100%;display: flex;">
        <div class="flex flex-row content-between gap-2 justify-between w-full h-min self-end text-ellipsis">
            <% if !domain.provisional %>
                <span class="px-2 py-0.5 bg-pink rounded uppercase">Live</span>
                <span class="rounded-full px-2 py-0.5 bg-blue uppercase">Manage →</span>
            <% else %>
                <span class="px-2 py-0.5 bg-yellow rounded uppercase" style="background: var(--lemon-glacier);border: 1px solid;">PROVISIONAL</span>
            <% end %>
        </div>
    </div>
</a>

app/views/domains/_todo.html.erb
<h1 class="font-heading text-4 text-pink leading-[1.5em]">
    <code>// TODO</code>
</h1>
<p class="text-1">We're still working on building this feature. Check back later or follow us <a class="link" href="https://social.dino.icu/@oblong">on the fediverse</a> for updates.</p>

app/views/domains/email.html.erb
<%= render "todo" %>

app/views/domains/index.html.erb
<% content_for :head do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>

<div class="flex flex-col items-center gap-8">

<h1 class="text-center text-blue text-4 lg:text-5 xl:text-6 font-heading">Manage your domains</h1>

<div class="grid grid-cols-1 gap-8 lg:grid-cols-3 xl:grid-cols-3">
  <% @domains.each do |domain| %>
    <% cache domain do %>
      <%= render domain %>
    <% end %>
  <% end %>

  <a href="/domains/request" class="flex flex-col p-4 gap-[1.375rem] bg-text text-black shadow-md rounded-2xl justify-center items-center h-full card" style="justify-content: center">
      <div style="background-color: rgb(65 234 212); border-radius: 99999px; padding: 0.5rem;">
        <svg width="40" height="40" style="fill: var(--bg);" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414" xmlns="http://www.w3.org/2000/svg" aria-label="plus" viewBox="0 0 32 32" preserveAspectRatio="xMidYMid meet" fill="currentColor" width="48" height="48" title="plus"><path d="M16,6c5.1,0 7.247,0.575 8.336,1.664c1.089,1.089 1.664,3.236 1.664,8.336c0,5.1 -0.575,7.247 -1.664,8.336c-1.089,1.089 -3.236,1.664 -8.336,1.664c-5.1,0 -7.247,-0.575 -8.336,-1.664c-1.089,-1.089 -1.664,-3.236 -1.664,-8.336c0,-5.1 0.575,-7.247 1.664,-8.336c1.089,-1.089 3.236,-1.664 8.336,-1.664Zm0,-2c10,0 12,2 12,12c0,10 -2,12 -12,12c-10,0 -12,-2 -12,-12c0,-10 2,-12 12,-12Zm-1,8c0,-0.552 0.448,-1 1,-1c0.552,0 1,0.448 1,1l0,3l3,0c0.552,0 1,0.448 1,1c0,0.552 -0.448,1 -1,1l-3,0l0,3c0,0.552 -0.448,1 -1,1c-0.552,0 -1,-0.448 -1,-1l0,-3l-3,0c-0.552,0 -1,-0.448 -1,-1c0,-0.552 0.448,-1 1,-1l3,0l0,-3Z"></path></svg>  
      </div>
      <h2 class="leading-none text-2" style="font-weight: 600">
        Request Domain
      </h2>
  </a>
  
  <% if @user.admin? %>
      <%= form_with url: domains_path, method: :post do |form| %>
        <div class="flex flex-col gap-2 p-4 shadow-md rounded-2xl admin" style="color: var(--bg);">
          <%= form.label :host, "Host:" %>
          <%= form.text_field :host %>
          <%= form.submit "Create domain" %>
        </div>
      <% end %>
  <% end %>
</div>

  <a href="<%= developers_applications_path %>" class="text-yellow developers">Developers →</a>

</div>

<%= style_tag nonce: true do %>
  input[type=text] {
    min-width: unset;
    color: var(--bg) !important;
    border-color: var(--bg) !important;
  }

  .developers {
    transition: ease-in-out 0.25s;
    font-size: 1.2rem;
  }

  .developers:hover {
    transform: translateX(1rem);
  }
<% end %>

app/views/domains/links.html.erb
<%= render "todo" %>

app/views/domains/new.html.erb
<h1>New Domain </h1>

<%= form_with model: Domain.new do |form| %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/domains/request_domain.html.erb
<h1 class="font-heading text-3 lg:text-4 xl:text-5">Request a subdomain</h1>
<br><br>
<%= form_with url: "/domains/provision" do |form| %>
    <%= form.label :host, "What domain are you requesting" %><br>
    <p>Just write the subdomain name - for example, if you wanted fionah.obl.ong, put "fionah" in the box below</p>
    <br>
    
    <span style="display: inline-flex;gap: 0.5rem;flex-wrap: nowrap;word-break: keep-all;"><%= form.text_field :host, placeholder: "fionah" %><span class="domain">.obl.ong</span></span>
    <br><br><br>
    <%= form.label :plan, "What are you planning on using it for?" %><br>
    <p>Don't worry, it doesn't need to be anything important or serious (it can be if you want though!)</p><br>
    <%= form.text_area :plan, placeholder: "I'm going to use my domain for a personal site" %>
    <br><br><br>
    <%= form.label :coc, "Do you agree to our Code of Conduct?" %><br>
    <p>We want to make sure our domains aren't used for bad purposes. Please read our Code of Conduct and Acceptable Use Policy: <a href="https://github.com/obl-ong/code-of-conduct">https://github.com/obl-ong/code-of-conduct</a></p>
    <br>
    <%= form.check_box :coc, required: true %>
    <br><br>

    <%= form.submit "Request" %>
<% end %>


<%= style_tag nonce: true do %>
    form {
        max-width: 50vw;
    }

    .domain {
        font-size: 2rem;
    }

    label {
        font-size: 2rem;
        font-weight: 600;
    }

    textarea {
        background-color: #f5f5f51a !important;
        border: 1.5px solid var(--cultured) !important;
        border-radius: 5px !important;
        color: #fff;
        min-width: 450px;
        min-height: 10rem;
    }

    a {
        color: var(--winter-sky);
    }
<% end %>

app/views/domains/settings.html.erb
<h1 class="admin-h2">Danger zone</h1>

<form method="DELETE" action="<%= domain_path(@domain) %>">
  <input class="btn-sm-pink" type="submit" value="Destroy" data-turbo-confirm="Are you sure you want to delete your domain? This action is permanent and irreversible.">
</form>

<% if @_current_user.admin? %>

  <div class="admin" style="margin-top: 1rem; padding: 0.5rem">

    <h2 class="admin-h2">Info</h2>
    <p>Last updated: <%= @domain.updated_at %></p>
    <p>First created: <%= @domain.created_at %></p>
    <p>Provisional? <%= @domain.provisional %></p>
    <br>
  
    <h2 class="admin-h2">Transfer</h2>
    <p>Current user: <%= @domain.user_users_id %>, <%=  User::User.find_by(id: @domain.user_users_id).email %></p>
    <br>
    <br>
    <%= form_with url: transfer_domain_path(@domain), method: :patch do |form| %>
      <%= form.text_field :new_user_id, placeholder: "New User's ID" %>
      <br><br>
      <%= form.submit "Transfer" %>
    <% end %>

  </div>
<% end %>

app/views/domains/show.html.erb
<h1><%= @domain.name + "." + Rails.application.config.suffix %></h1>
<ul>
  <% @domain.resources.each do |r| %>
    <li><%= r.type %> <%= r.name %></li>
  <% end %>
</ul>
<%= link_to "New Resource", new_domain_resource_path(@domain.name) %>