config/routes.rb
# typed: true

Rails.application.routes.draw do
  use_doorkeeper_openid_connect
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end
  use_doorkeeper_device_authorization_grant do
    controller device_authorizations: "device_authorizations"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/oauth/device/approve", to: "device_authorizations#approve"
  delete "/oauth/device/destroy", to: "device_authorizations#destroy"

  get "up" => "rails/health#show", :as => :rails_health_check

  resources :domains, param: :host, except: [:new] do
    collection do
      get "request", to: "domains#request_domain"
      post "provision", to: "domains#provision"
    end

    member do
      get "/", to: "records#index"
      get "email"
      get "links"
      get "settings"
      get "show", as: "show"
      patch "transfer"
      resources :records
    end
  end

  scope :admin do
    get "/", to: "admin#index"

    scope :users do
      get "/", to: "admin#users"
      get "/:id/domains", to: "admin#users_domains", as: "admin_users_domains"
    end

    scope :domains do
      get "/", to: "admin#domains"
      get "/review", to: "admin#review"
      post "/review", to: "admin#review_decision"
    end

    scope :developers do
      post "/review", to: "admin#developers_review_decision"
      get "/review", to: "admin#developers_review"
    end

    resources :broadcasts, only: [:index], shallow: true do
      resources :notices
      resources :announcements
    end

    mount MissionControl::Jobs::Engine, at: "/jobs"
    mount Audits1984::Engine => "/console"
  end

  get "users/register"
  post "users/create"
  get "users/email_verification"
  post "users/verify_email"
  patch "users/update"

  get "settings", to: "users#settings"

  get "auth/create_key"
  patch "auth/add_key"
  delete "auth/destroy_key"

  get "auth/login"
  get "auth/logout"
  get "auth/email", as: "auth_email"
  post "auth/verify_code", as: "verify_code"
  patch "auth/update_email_auth"
  # need to send request body, made it POST
  post "auth/verify_key"

  get "auth/unsupported"

  # Defines the root path route ("/")
  root "domains#index"

  namespace :api do
    namespace :v1 do
      resources :domains, param: :host do
        member do
          resources :records, module: "domains"
        end
      end
      get "user", to: "user#show"
      patch "user", to: "user#update"
    end
  end

  namespace :developers do
    get "/", to: redirect("developers/applications")
    resources :applications do
      member do
        post "scopes", to: "applications#add_scope"
        delete "scopes", to: "applications#destroy_scope"

        post "redirect_uris", to: "applications#add_redirect_uri"
        delete "redirect_uris", to: "applications#destroy_redirect_uri"
      end

      collection do
        get "request", to: "applications#request"
        post "provision", to: "applications#provision"
      end
    end
  end
end

app/controllers/device_authorizations_controller.rb
class DeviceAuthorizationsController < Doorkeeper::ApplicationController
  before_action :authenticate_resource_owner!

  def index
  end

  def approve
    session[:device_grant_id] = nil
    device_grant = device_grant_model.lock.find_by(user_code: user_code)
    if device_grant.nil?
      authorization_error_response(:invalid_user_code)
      return
    end
    if device_grant.expired?
      authorization_error_response(:expired_user_code)
    end
    session[:device_grant_id] = device_grant.id

    @client = Doorkeeper::Application.find_by(id: device_grant.application_id)
    @scopes = device_grant.scopes.split(" ")
  end

  def authorize
    device_grant_model.transaction do
      device_grant_model.lock.find_by(id: session[:device_grant_id]).update!(user_code: nil, resource_owner_id: current_resource_owner.id)

      render "success"
    end
  end

  def destroy
    device_grant_model.lock.find_by(id: session[:device_grant_id]).destroy # standard:disable Rails/SaveBang
    render plain: "The authorization request was denied"
  end

  def success
  end

  private

  def authorization_success_response
    respond_to do |format|
      notice = I18n.t(:success, scope: i18n_flash_scope(:authorize))
      format.html { redirect_to oauth_device_authorizations_index_url, notice: notice }
      format.json { head :no_content }
    end
  end

  # @param error_message_key [Symbol]
  def authorization_error_response(error_message_key)
    respond_to do |format|
      notice = I18n.t(error_message_key, scope: i18n_flash_scope(:authorize))
      format.html { redirect_to oauth_device_authorizations_index_url, notice: notice }
      format.json do
        render json: {errors: [notice]}, status: :unprocessable_entity
      end
    end
  end

  # @return [Class]
  def device_grant_model
    @device_grant_model ||= Doorkeeper::DeviceAuthorizationGrant.configuration.device_grant_model
  end

  # @return [String, nil]
  def user_code
    params[:user_code]
  end

  # @param action [Symbol]
  # @return [Array<Symbol>]
  def i18n_flash_scope(action)
    %I[doorkeeper flash device_codes #{action}]
  end
end

app/helpers/device_authorizations_helper.rb
module DeviceAuthorizationsHelper
end

app/views/device_authorizations/approve.html.erb
<main>
  <section role="main">
    <%= image_tag "oval.svg", size: "200" %>
    <h1><%= raw t('doorkeeper.authorizations.new.title', client_name: content_tag(:strong, class: 'text-info') { @client.name }) %></h1>
    <h2>
      <%= raw t('doorkeeper.authorizations.new.prompt', client_name: content_tag(:strong, class: 'text-info') { @client.name }) %>
    </h2>

    <% if @scopes.count > 0 %>
      <div id="oauth-permissions">
        <h2><%= t('doorkeeper.authorizations.new.able_to') %>:</h2>

        <ul class="text-info">
          <% @scopes.each do |scope| %>
            <li>✓ <%= raw t scope, scope: [:doorkeeper, :scopes] %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="actions">
      <%= form_tag oauth_device_authorizations_authorize_url, method: :post do %>
        <%= submit_tag t('doorkeeper.authorizations.buttons.authorize'), class: "btn btn-success btn-lg btn-block" %>
      <% end %>
      <%= form_tag oauth_device_destroy_path, method: :delete do %>
        <%= submit_tag t('doorkeeper.authorizations.buttons.deny'), class: "btn btn-danger btn-lg btn-block" %>
      <% end %>
    </div>
  </section>
</main>

<%= style_tag nonce: true do %>
	main {
		padding: 5rem;
		padding-top: 4rem;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 1rem;
		min-height: 100vh;
	}

	.error {
		font-style: italic;
		color: var(--lemon-glacier);
	}

	h1 {
		font-weight: 300;
		font-size: 2.5rem;
		padding: 0;
		margin: 0;
	}

  h2 {
    font-size: 1.2rem;
  }

	div {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	a {
		color: var(--winter-sky);
	}

	a:hover {
		font-style: italic;
	}
	
	b {
		font-weight: 700; 
	}
	
	form {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	section {
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
		align-items: center;
		text-align: center;
	}

  strong {
    font-weight: 700;
  }

  ul {
    text-align: left;
    max-width: 500px;
  }

  li {
    padding: 0.5rem 0.25rem;
    font-size: 1.25rem;
  }

  .actions {
    display: flex;
    flex-direction: row;
  }

  .btn-danger {
    background-color: var(--bg) !important;
    border: 2px solid var(--winter-sky);
  }
<% end %>

app/views/device_authorizations/index.html.erb
<main>
  <section role="main">
    <%= image_tag "oval.svg", size: "200" %>
    <h1>Connect a device</h1>
    <h2>
      Enter the code displayed on your device
    </h2>

    <div class="actions">
      <%= form_with url: oauth_device_approve_url, method: :get do |form| %>
        <%= form.text_field :user_code, class: 'form-control', placeholder: "Code" %>
        <%= form.submit "Connect", class: "btn btn-success btn-lg btn-block" %>
      <% end %>
    </div>
  </section>
</main>

<%= style_tag nonce: true do %>
	main {
		padding: 5rem;
		padding-top: 4rem;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 1rem;
		min-height: 100vh;
	}

	.error {
		font-style: italic;
		color: var(--lemon-glacier);
	}

	h1 {
		font-weight: 300;
		font-size: 2.5rem;
		padding: 0;
		margin: 0;
	}

  h2 {
    font-size: 1.2rem;
  }

	div {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	a {
		color: var(--winter-sky);
	}

	a:hover {
		font-style: italic;
	}
	
	b {
		font-weight: 700; 
	}
	
	form {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	section {
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
		align-items: center;
		text-align: center;
	}

  strong {
    font-weight: 700;
  }

  ul {
    text-align: left;
    max-width: 500px;
  }

  li {
    padding: 0.5rem 0.25rem;
    font-size: 1.25rem;
  }

  .actions {
    display: flex;
    flex-direction: row;
  }

  .btn-danger {
    background-color: var(--bg) !important;
    border: 2px solid var(--winter-sky);
  }
<% end %>

app/views/device_authorizations/success.html.erb
<main>
  <section role="main">
    <%= image_tag "oval.svg", size: "200" %>
    <h1>Authorization successful!</h1>
    <h2>
      You can close this tab safely.
    </h2>
</main>

<%= style_tag nonce: true do %>
	main {
		padding: 5rem;
		padding-top: 4rem;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 1rem;
		min-height: 100vh;
	}

	.error {
		font-style: italic;
		color: var(--lemon-glacier);
	}

	h1 {
		font-weight: 300;
		font-size: 2.5rem;
		padding: 0;
		margin: 0;
	}

  h2 {
    font-size: 1.2rem;
  }

	div {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	a {
		color: var(--winter-sky);
	}

	a:hover {
		font-style: italic;
	}
	
	b {
		font-weight: 700; 
	}
	
	form {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	section {
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
		align-items: center;
		text-align: center;
	}

  strong {
    font-weight: 700;
  }

  ul {
    text-align: left;
    max-width: 500px;
  }

  li {
    padding: 0.5rem 0.25rem;
    font-size: 1.25rem;
  }

  .actions {
    display: flex;
    flex-direction: row;
  }

  .btn-danger {
    background-color: var(--bg) !important;
    border: 2px solid var(--winter-sky);
  }
<% end %>